		LIST P=16F877A
		RADIX HEX
		#include <p16F877a.inc>
		__CONFIG  _CP_OFF &_WDTE_OFF & _PWRTE_OFF & _HS_OSC & _CPD_OFF & _LVP_OFF & _BOREN_OFF & _WRT_OFF & _DEBUG_OFF
		

	    contador  EQU 0X10	
		;VARIABLES ADC
        RESULTADO1  EQU 0X20
		DATO_USART	EQU 0X21
		CONT		EQU 0X30
		RELOJ       EQU 0X40

		

		MAIN 	CODE 0X0000
		GOTO CODIGO_PRINCIPAL

;--------------------------------------------------------------------------------------
ORG 0X0004     ;Aqui inicia el vector de las interrupciones
		BCF INTCON, GIE
		BANKSEL PIR1
		BTFSC 	PIR1, TMR1IF
	    GOTO 	INT_TIMER1
		BTFSC	PIR1, ADIF
		GOTO	INT_ADC
		BTFSC	PIR1, RCIF
		GOTO	INT_USART
		GOTO	REGRESO_INT		


INT_TIMER1                  ;MANEJO INT TIMER1
		BCF PIR1, TMR1IF	;Limpiamos la bandera
		
		;Aqui manejamos la interrupción cuando ocurra
		INCF   RELOJ		
        BANKSEL TMR1L
		MOVLW  0xDA
		MOVWF  TMR1L
		MOVLW  0x0B
		MOVWF  TMR1H	

		;Salida de la interrupción
		GOTO REGRESO_INT

INT_ADC
		BCF PIR1, ADIF	
		BANKSEL ADRESH
		MOVF 	ADRESH,W	 ;OJO ya no tenemos que esperar
		MOVWF 	RESULTADO1	 ;OBTENER RESULTADO	

		BANKSEL TXREG
		MOVF  RESULTADO1, W
		MOVWF TXREG
		
		;Salida de la interrupción
		GOTO REGRESO_INT


INT_USART
		BCF 	PIR1, RCIF
		BANKSEL RCREG
		MOVF	RCREG, W
		MOVWF	DATO_USART

		BANKSEL	PORTB
		MOVF  	DATO_USART, W
		MOVWF 	PORTB

		;Salida de la interrupción
		GOTO REGRESO_INT
			
REGRESO_INT				;Aqui activamos las interrupciones de nuevo
		BSF INTCON, GIE	;y regresamos donde iba el programa
		RETFIE

;-------------------------------------------------------------------------------------


CODIGO_PRINCIPAL
		CLRW

		BANKSEL PORTA
		CLRF    PORTA
		CLRF    PORTB
		CLRF 	PORTD

		BANKSEL ADCON1
		MOVLW B'01001110' 
		MOVWF ADCON1

		BANKSEL ADCON0
		MOVLW B'10000001' 
		MOVWF ADCON0
		CALL  DELAY

		BANKSEL TRISA
		CLRF    TRISA
		CLRF    TRISB
		CLRF	TRISD
		BSF     TRISA, 1
		BSF     TRISA, 0
		BSF		TRISC, 6 ;TX
		BSF		TRISC, 7 ;RX

		BANKSEL PORTB
		CLRF    PORTB
		CLRF 	PORTD

		BANKSEL T1CON
		MOVLW B'00110001'  
		MOVWF   T1CON

		;CONFIGURACION PUERTO SERIAL--------------------------------------------

		;BAUD RATE
		BANKSEL SPBRG
		MOVLW   D'129' 
		MOVWF   SPBRG

		;COMUNICACION ASINCRONA
		BANKSEL TXSTA
		BCF TXSTA, BRGH
		BCF TXSTA, SYNC
		BANKSEL RCSTA
		BSF     RCSTA, SPEN
	
		;HABILITAR LA TRANSMISION DE DATOS
		BANKSEL TXSTA
		BCF TXSTA, TX9
		BSF TXSTA, TXEN
	
		;HABILITAR LA RECEPCION DE DATOS
		BANKSEL RCSTA
		BCF RCSTA, RX9
		BSF RCSTA, CREN
		;-------------------------------------------------------------------------

		;AQUI HABILITAMOS LAS INTERRUPCIONES
		BANKSEL PIE1
		BSF PIE1, TMR1IE    	;INT Timer1
		BSF PIE1, ADIE			;INT ADC
		BSF PIE1, RCIE			;INT USART RX
		BANKSEL INTCON
		BSF INTCON, PEIE        ;INT Perifericos
		BSF INTCON, GIE			;INT Globales

		BANKSEL TMR1L
		MOVLW  0xDA
		MOVWF  TMR1L
		MOVLW  0x0B
		MOVWF  TMR1H
	

INICIO
		BANKSEL ADCON0
		BCF 	ADCON0, CHS0 ;COLOCA CHANNEL 0
		BSF 	ADCON0, GO	 ;EMPIEZA A CONVERTIR
		CALL 	DELAY
		
		CALL  TOGGLE
		GOTO  INICIO

TOGGLE 	
		MOVLW 4
		SUBWF RELOJ, 0
		BTFSS STATUS, Z
		RETURN
		CLRF  RELOJ
		MOVLW 9
		SUBWF PORTD, 0
		BTFSC STATUS, Z
		GOTO  RESETCOUNTER
		INCF PORTD, 1
		RETURN
RESETCOUNTER
		CLRF PORTD
		RETURN
		

DELAY
	CLRF 	CONT
	MOVLW 	0A  ;COLOCA 200 EN EL CONTADOR
	MOVWF 	CONT
CICLO1
	DECF 	CONT, 1	;DECREMENTA HASTA QUE SEA CERO Y SALE DEL CICLO
	BTFSS 	STATUS, Z
	GOTO 	CICLO1
	
	RETURN


	END
 