;UNIVERSIDAD RAFAEL LANDIVAR
;FACULTAD DE INGENIERIA
;ARQUITECTURA DEL COMPUTADOR 1 , CICLO 1,2022
;LAB 7
;ALUMNO JULIO RUIZ, CESAR SILVA
;MÓDULACIÓN POR ANCHO DE PULSOS(PWM)

;FUNCIONALIDAD
;Construya un circuito de que sea capaz de modificar el nivel lumínico de 2 luces LED,
;mediante una señal de control analógica. Este circuito deberá realizar las siguientes 
;funciones:
;Cambiar el nivel de intensidad lumínico de LED No. 1, mediante una señal PWM
;creada usando un módulo PWM en el PIC.
;Implementar una señal PWM por software para controlar el nivel lumínico de LED
;No. 2
;Leer una señal analógica de salida de potenciómetro y usar dicha medida de 
;referencia para cambiar el nivel lumínico de ambos LEDS.
LIST P=16F877A
RADIX HEX
#include <p16F877a.inc>
__CONFIG  _CP_OFF &_WDTE_OFF & _PWRTE_OFF & _HS_OSC & _CPD_OFF & _LVP_OFF & _BOREN_OFF & _WRT_OFF & _DEBUG_OFF
		

        RESULTADO1  EQU 0X20
        RESULTADO2  EQU 0X21
        POS1   EQU 0X30

        CONT   EQU 0X31
        RELOJ   EQU 0X32

        CONTADOR1   EQU 0X33
        CONTADOR2   EQU 0X34
        CONTADOR3   EQU 0X35
        CONTADOR4   EQU 0X36

        CONTADOR5   EQU 0X43
        CONTADOR6   EQU 0X44
        CONTADOR7   EQU 0X45
        CONTADOR8   EQU 0X46

        CONTADOR9   EQU 0X53
        CONTADOR10   EQU 0X54
        CONTADOR11   EQU 0X55
        CONTADOR12   EQU 0X56

         CONTADOR13   EQU 0X63
        CONTADOR14   EQU 0X64
        CONTADOR15   EQU 0X65
        CONTADOR16   EQU 0X66



ORG 0
CLRW
	BANKSEL PORTA
	CLRF    PORTA
	CLRF    PORTB
	CLRF    PORTD
	
	BANKSEL ADCON1
	MOVLW B'01000100' ;BIT 0-3  = PCFG3-> A/D CONFI PUERTO
		                ;BIT 4-6 = UNIMPLEMENTED -> LEE -0
        	 	                ;BIT 7 = ADFM -> 0 JUSTIFICADO ALA IZQUIERDA SIGNIFFICA QUE LOS BITS MAS SIGNIFICATIVOS ESTAN CORRIDOS AL REGISTRO H
	MOVWF ADCON1

	BANKSEL ADCON0
	MOVLW B'10001001' ; BIT 0 ->SI ESTA EN 1 A/D MODULO CONVERTIDOR OPERANDO
                                                                ;BIT 3-5 ->001 CHANEL 1(RA1/AN1)
		               ;BIT 7-6 ->10 FOSC/32
	MOVWF ADCON0
	CALL  DELAY
	
	BANKSEL PR2 ; EL VALOR DEL TIMER2(EL PERIODO DEL REGISTRO) QUE VA A CONTAR
	MOVLW   D'255' ;PWM
	MOVWF  PR2   ;EL TMR2 ES DE 8 BITS
	
	BANKSEL CCPR1L
	MOVLW B'01011110'  
	MOVWF  CCPR1L
		       
	BANKSEL CCP1CON
	MOVLW B'00001100' ;BIT 3-0 -> 11XX = PWM MODE
	MOVWF  CCP1CON
	
	BANKSEL CCPR2L  
	MOVLW B'00111100' 
	MOVWF  CCPR2L
      
	BANKSEL T2CON
	MOVLW B'00000111' ; 1:1 POSTCALE ->BIT 6-3
	MOVWF  T2CON	
		
	BANKSEL TRISA
	CLRF    TRISA
	CLRF    TRISC
	CLRF    TRISD
			
	BSF     TRISA, 0
	BSF     TRISA, 1
		   	
	MOVLW   B'11111110'
	MOVWF   TRISB
       
	BANKSEL PORTB
	CLRF    PORTB
	CLRF    PORTC
	CLRF    PORTD
	
	BANKSEL T1CON 
	MOVLW B'00110001'  ;BIT1 -ENCIENDE EL TIMER1, BIT 5,4 1:8 PRESCALE VALUE
	MOVWF   T1CON
	
	BANKSEL TMR1L ;TMR1 = 16 BITS Y SE PARTE EN 2 REGISTROS QUE SON EL L Y H
	MOVLW  0xDA
	MOVWF  TMR1L
	MOVLW  0x0B
	MOVWF  TMR1H
	
INICIO
	CALL  ADC_1 ;LED VERDE=>PWM
	BTFSC PORTB,1;AQUI SE ACTIVA PARA ACCIONAR LOS DOS LEDS
	CALL  ADC_2
	BTFSC PORTB,2;AQUI SE ACTIVA EL LED ROJO PARA TRABAJARLO MANUAL
	GOTO  LED_MANUAL
			
	BANKSEL TMR1H
	MOVLW 1
	SUBWF TMR1H, 0
	BTFSC STATUS, Z
	CALL  TOGGLE
	GOTO  INICIO

LED_MANUAL
	BTFSC    PORTB,3          ;SE COMPRUEBA SI EL PIN 4 DEL PUERTO B HA SIDO PRESIONADA
	CALL     INTENSIDAD_1      ;CASO SEA VERDADERO
	BTFSC    PORTB,4          ;SE COMPRUEBA SI EL PIN 5 DEL PUERTO B HA SIDO PRESIONADA
	CALL     INTENSIDAD_2      ;CASO SEA VERDADERO
	GOTO  INICIO

INTENSIDAD_1 ;INTESIDAD BAJA
	BSF       PORTC,1
	CALL     DELAY_5MS  ;3 de 5 para hacer 15ms
                        CALL     DELAY_5MS
                        CALL     DELAY_5MS
                        ;CALL     DELAY_5MS
	BCF       PORTC,1
	CALL     DELAY_5MS ;3 de 5 para hacer 15ms
	CALL     DELAY_5MS
                        CALL     DELAY_5MS
	RETURN    

INTENSIDAD_2 ;INTENSIDAD ALTA
	BSF       PORTC,1
	CALL     DELAY_25MS
	CALL     DELAY_5MS
	RETURN    

TOGGLE 	
	INCF   RELOJ
	BANKSEL TMR1L
	MOVLW  0xDA
	MOVWF  TMR1L
	MOVLW  0x0B
	MOVWF  TMR1H	  
	RETURN

ADC_1
	BANKSEL ADCON0
	BCF  ADCON0, CHS0 ;COLOCA CHANNEL 0
	BSF ADCON0, GO	 ;EMPIEZA A CONVERTIR
	BTFSC ADCON0, GO
	GOTO $-1 ;YA TERMINO?

	BANKSEL ADRESH
	MOVF ADRESH,W
	MOVWF RESULTADO1 ;OBTENER RESULTADO
	BANKSEL CCPR1L
   	MOVFW RESULTADO1
   	MOVWF CCPR1L ;ES EL PUERTO DE SALIDA EL TREN DE PULSOS

                        CALL  DELAY
	RETURN
;HAY DOS ADC PARA ENCENDER EL SEGUNDO LED
;EL ADC PARA LA SEGUNDA LED ES NECESARIA PARA QUE ENCIENDAD LAS DOS LED CON 
;EL POTENCIOMETRO
ADC_2
	BANKSEL ADCON0
	BCF ADCON0, CHS0 ;COLOCA CHANNEL 0
	BSF ADCON0, GO  ;EMPIEZA A CONVERTIR
	BTFSC ADCON0, GO
	GOTO $-1 ;YA TERMINO?

	BANKSEL ADRESH
	MOVF ADRESH,W
	MOVWF RESULTADO2 ;OBTENER RESULTADO
   
;AQUI SE HABILITA LA SALIDA DEL CCP2
	BTFSC   PORTB,1
	BANKSEL CCPR2L
	BTFSC   PORTB,1  ;;;
	BANKSEL CCP2CON  ;;;      ;BIT 3-0 -> 11XX = PWM MODE
	BTFSC   PORTB,1 ;;;;
	MOVLW B'00001100' ;;
	BTFSC   PORTB,1 ;;;;
	MOVWF  CCP2CON  ;;;;
	BTFSC   PORTB,1
	MOVFW RESULTADO2
	BTFSC   PORTB,1
	MOVWF  CCPR2L	   
	CALL DELAY

	RETURN

DELAY_1MS

;PIC Time Delay = 0.00105800 s with Osc = 4000000 Hz
		movlw	D'2'
		movwf	CONTADOR15
		movlw	D'93'
		movwf	CONTADOR16
loop_1		decfsz	CONTADOR16,1
		goto	loop_1
		decfsz	CONTADOR15,1
		goto	loop_1
		retlw	0



DELAY_4MS
;PIC Time Delay = 0.00405700 s with Osc = 4000000 Hz
		movlw	D'6'
		movwf	CONTADOR11
		movlw	D'66'
		movwf	CONTADOR12
loop_2		decfsz	CONTADOR12,1
		goto	loop_2
		decfsz	CONTADOR11,1
		goto	loop_2
		retlw	0

DELAY_5MS
;PIC Time Delay = 0.00505800 s with Osc = 4000000 Hz
		movlw	D'7'
		movwf	CONTADOR3
		movlw	D'143'
		movwf	CONTADOR4
loop_3		decfsz	CONTADOR4,1
		goto	loop_3
		decfsz	CONTADOR3,1
		goto	loop_3
		retlw	0

DELAY_25MS
;PIC Time Delay = 0.02505100 s with Osc = 4000000 Hz
		movlw	D'33'
		movwf	CONTADOR7
		movlw	D'134'
		movwf	CONTADOR8
loop_4		decfsz	CONTADOR8,1
		goto	loop_4
		decfsz	CONTADOR7,1
		goto	loop_4
		retlw	0

	
DELAY
	CLRF 	CONT
	MOVLW 	0A  ;COLOCA 200 EN EL CONTADOR
	MOVWF 	CONT
CICLO1
	DECF 	CONT, 1	;DECREMENTA HASTA QUE SEA CERO Y SALE DEL CICLO
	BTFSS 	STATUS, Z
	GOTO 	CICLO1
	
	RETURN


END
